---

- name: Add Inventories
  ansible.controller.inventory:
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username }}"
    controller_password: "{{ aap_controller_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }} (Created by Ansible)"
    organization: "{{ item.organization | default('Default') }}"
    state: "{{ item.state | default('present') }}"
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ aap_inventories }}"

- name: Add Inventory sources
  ansible.controller.inventory_source:
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username }}"
    controller_password: "{{ aap_controller_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }} (Created by Ansible)"
    organization: "{{ item.organization | default('Default') }}"
    state: "{{ item.state | default('present') }}"
    inventory: "{{ item.inventory }}"
    source: "{{ item.source }}"
    host_filter: "{{ item.host_filter | default(omit) }}"
    credential: "{{ item.credential }}"
    overwrite: "{{ item.overwrite | default('true') }}"
    update_on_launch: "{{ item.update_on_launch | default('true') }}"
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ aap_inventory_sources }}"

...