---

- name: Add Organizations
  awx.awx.organization:
    controller_host: "{{ awx_host }}"
    controller_username: "{{ awx_username }}"
    controller_password: "{{ awx_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }} (Created by Ansible)"
    state: "{{ item.state | default('present') }}"
    galaxy_credentials: "{{ item.galaxy_credentials | default(omit) }}"
    validate_certs: false
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ awx_organizations }}"
