---

- name: Add Inventories
  awx.awx.inventory:
    controller_host: "{{ awx_host }}"
    controller_username: "{{ awx_username }}"
    controller_password: "{{ awx_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }} (Created by Ansible)"
    organization: "{{ item.organization | default('Default') }}"
    state: "{{ item.state | default('present') }}"
    validate_certs: false
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ awx_inventories }}"

...
