---

- name: Add Hosts
  ansible.controller.host:
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username }}"
    controller_password: "{{ aap_controller_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }} (Created by Ansible)"
    inventory: "{{ item.inventory }}"
    variables: "{{ item.variables | default(omit) }}"
    enabled: "{{ item.enabled | default('true') }}"
    state: "{{ item.state | default('present') }}"
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ aap_hosts }}"

...