---

- name: Add Projects
  awx.awx.project:
    controller_host: "{{ awx_host }}"
    controller_username: "{{ awx_username }}"
    controller_password: "{{ awx_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }} (Created by Ansible)"
    organization: "{{ item.organization | default('Default') }}"
    state: "{{ item.state | default('present') }}"
    scm_update_on_launch: "{{ item.scm_update_on_launch | default(omit) }}"
    scm_update_cache_timeout: "{{ item.scm_update_cache_timeout | default(omit) }}"
    scm_type: "{{ item.scm_type | default('git') }}"
    scm_branch: "{{ item.scm_branch | default('master') }}"
    scm_url: "{{ item.scm_url | default(omit) }}"
    credential: "{{ item.credential | default(omit) }}"
    validate_certs: false
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ awx_projects }}"
