---

- name: Add Credentials
  ansible.controller.credential:
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username }}"
    controller_password: "{{ aap_controller_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }} (Created by Ansible)"
    organization: "{{ item.organization | default('Default') }}"
    credential_type: "{{ item.credential_type }}"
    state: "{{ item.state | default('present') }}"
    inputs: "{{ item.inputs }}"
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ aap_credentials }}"
