---

- name: Add Job Templates
  awx.awx.job_template:
    controller_host: "{{ awx_host }}"
    controller_username: "{{ awx_username }}"
    controller_password: "{{ awx_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }} (Created by Ansible)"
    organization: "{{ item.organization | default('Default') }}"
    state: "{{ item.state | default('present') }}"
    credential: "{{ item.credential | default(omit) }}"
    job_type: "{{ item.job_type }}"
    inventory: "{{ item.inventory }}"
    forks: "{{ item.forks | default(omit) }}"
    project: "{{ item.project }}"
    playbook: "{{ item.playbook }}"
    credentials: "{{ item.credentials }}"
    job_tags: "{{ item.job_tags | default(omit) }}"
    skip_tags: "{{ item.skip_tags | default(omit) }}"
    limit: "{{ item.limit | default(omit) }}"
    ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(omit) }}"
    ask_extra_vars: "{{ item.ask_extra_vars | default(omit) }}"
    extra_vars: "{{ item.extra_vars | default(omit) }}"
    ask_credential_on_launch: "{{ item.ask_credential_on_launch | default(omit) }}"
    allow_simultaneous: "{{ item.allow_simultaneous | default('true') }}"
    use_fact_cache: "{{ item.use_fact_cache | default('true') }}"
    become_enabled: "{{ item.become_enabled | default('true') }}"
    execution_environment: "{{ item.execution_environment | default(omit) }}"
    survey_enabled: "{{ item.survey_enabled | default(omit) }}"
    survey_spec: "{{ item.survey_spec | default(omit) }}" #https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Job_Templates/Job_Templates_job_templates_survey_spec_create
    validate_certs: false
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ awx_jobtemplates }}"
