---

- name: Add Credentials
  awx.awx.credential:
    controller_host: "{{ awx_host }}"
    controller_username: "{{ awx_username }}"
    controller_password: "{{ awx_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }} (Created by Ansible)"
    organization: "{{ item.organization | default('Default') }}"
    credential_type: "{{ item.credential_type }}"
    state: "{{ item.state | default('present') }}"
    inputs: "{{ item.inputs }}"
    validate_certs: false
  no_log: "{{ no_logging | default ('true') }}"
  loop: "{{ awx_credentials }}"
