- hosts: awx
  gather_facts: no
  vars_files:
    - ../vars/main.yaml
    - ../vars/vault.yaml
    - ../vars/settings.yaml
    - ../vars/credentials.yaml
    - ../vars/projects.yaml
    - ../vars/hosts.yaml
    - ../vars/groups.yaml
    - ../vars/inventories.yaml
    - ../vars/jobtemplates.yaml
    - ../vars/schedules.yaml
    - ../vars/organizations.yaml
    - ../vars/notification_templates.yaml
    - ../vars/execution_environments.yaml
  tasks:
    - name: No tags warn
      pause:
        prompt: "Tags should be specified to control execution, running without tags will activate all available tasks"
        seconds: 20
      when: "'all' in ansible_run_tags"

    - import_tasks: ../tasks/configure_settings.yaml
      tags: [aap_settings]

    - import_tasks: ../tasks/configure_organizations.yaml
      tags: [aap_organizations]

    - import_tasks: ../tasks/configure_credentials.yaml
      tags: [aap_credentials]

    - import_tasks: ../tasks/configure_execution_environments.yaml
      tags: [aap_execution_environments]

    - import_tasks: ../tasks/configure_notification_templates.yaml
      tags: [aap_notification_templates]

    - import_tasks: ../tasks/configure_projects.yaml
      tags: [aap_projects]

    - import_tasks: ../tasks/configure_inventories.yaml
      tags: [aap_inventories]

    - import_tasks: ../tasks/configure_hosts.yaml
      tags: [aap_hosts]

    - import_tasks: ../tasks/configure_groups.yaml
      tags: [aap_groups]

    - import_tasks: ../tasks/configure_jobtemplates.yaml
      tags: [aap_jobtemplates]

    - import_tasks: ../tasks/configure_schedules.yaml
      tags: [aap_schedules]

