- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars/vault.yaml
    - ../vars/credentials.yaml
    - ../vars/projects.yaml
    - ../vars/inventories.yaml
    - ../vars/jobtemplates.yaml
    - ../vars/organizations.yaml
  tasks:
    - name: No tags warn
      pause:
        prompt: "Tags should be specified to control execution, running without tags will activate all available tasks"
        seconds: 20
      when: "'all' in ansible_run_tags"


    - import_tasks: ../tasks/configure_organizations.yaml
      tags: [awx_organizations]

    - import_tasks: ../tasks/configure_credentials.yaml
      tags: [awx_credentials]

    - import_tasks: ../tasks/configure_projects.yaml
      tags: [awx_projects]

    - import_tasks: ../tasks/configure_inventories.yaml
      tags: [awx_inventories]

    - import_tasks: ../tasks/configure_jobtemplates.yaml
      tags: [awx_jobtemplates]


