name: Deploy projects
run-name: Deploy projects on AWX
on:
  push:
    branches:
    - main

kobs:
  changes:
    runs-on: self-hosted
    outputs:
      src: ${{ steps.changes.outputs.src }}
      infra: ${{ steps.changes.outputs.infra }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          vars:
            - 'vars/projects.yaml'

  vars:
    needs: changes
    if: ${{ needs.changes.outputs.vars == 'true' }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: echo "projects was changed"
