name: Deploy projects
run-name: Deploy projects on AWX
on:
  push:
    branches:
    - main

jobs:
  changes:
    runs-on: self-hosted
    outputs:
      vars: ${{ steps.changes.outputs.vars }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          vars:
            - 'vars/projects.yaml'

  vars:
    needs: changes
    if: ${{ needs.changes.outputs.vars == 'true' }}
    runs-on: self-hosted
    steps:
    - run: curl -k -X POST -u ${{ secrets.AWX_USER }}:${{ secrets.AWX_PASSWORD }} https://awx.baluba.net/api/v2/workflow_job_templates/11/launch/
